### ISSUE TITLE
Processor 'ucto.1' is used for annotationtype 'paragraph' but there is no corresponding <annotator> referring to it in the annotation declaration block.

### ISSUE THREAD

**Issue by proycon** [LanguageMachines/ucto#70] opened 2019-07-15 10:26 UTC
Something goes wrong when ucto internally assigns processors to process a FoLiA document (untokenised, but with paragraph and various other structures):

Input file: ``mlp05:/scratch/proycon/ucto70.folia.xml``

```
$ ucto -L "nld-historical" -X -F ucto70.folia.xml ucto70_out.folia.xml
```

```
  ucto: --filter=NO is automatically set. inputclass equals outputclass!
  ucto: inputfile = _sid001boek01_01.withmetadata.folia.xml
  ucto: outputfile = _sid001boek01_01.tok.folia.xml
  ucto:configured TEXTCAT( /vol/customopt/lamachine16.dev/share/ucto/textcat.cfg )
  ucto:ucto: --filter=NO is automatically set. inputclass equals outputclass!
  ucto: XML error: Processor 'ucto.1' is used for annotationtype 'paragraph' but there is no corresponding <annotator> referring to it in the annotation declaration block.
```

**Comment by kosloot** [comment] 2019-07-15 14:06
I see.
I constructed a simpler example to reproduce this:
[issue70.xml.txt](https://github.com/LanguageMachines/ucto/files/3392552/issue70.xml.txt)

The problem is then created by this declaration: 
```xml
      <paragraph-annotation set="https://raw.githubusercontent.com/proycon/folia/master/setdefinitions/tei2folia/paragraphs.fol
iaset.ttl">
        <annotator processor="proc.tei2folia.xsl"/>
      </paragraph-annotation>
```

in combination with:
```xml
         <cell xml:id="issue70.text.div.1.table.1.row.1.cell.1">
            <t>Barth. Anglicus =</t>
          </cell>
```

When tokenizing this text, ucto wants to create a new Paragraph containing the two Sentences around 'Bart.' and 'Anglicus'

At the moment ucto does not use a setname for Paragraphs, Sentences and Quotes. (only for Tokens)
But then it will default to the already declared setname "https://raw.githubusercontent.com/proycon/folia/master/setdefinitions/tei2folia/paragraphs.foliaset.ttl"

But that setname is NOT associated with the newly created "ucto.1" processor. And we are in trouble.

I don't want to start using setnames for Paragraphs and such created by ucto. But I am not sure what a good solution should be.
 I assume that adding a paragraph-annotation with an empty set should "invalidate" the  defaultset for paragraphs.
So maybe a bug in Libfolia. Needs some thinking.

@proycon comments welcome!

**Comment by proycon** [comment] 2019-07-15 14:36
Hmm, this is indicative of a problem in FoLiA itself perhaps even. Certain annotation types can be setless or carry a set, but they can't co-exist. It seems we do have a use-case for this now though and the best solution is probably to make it so FoLiA can handle it. I'll create a new issue.

**Comment by kosloot** [comment] 2019-07-16 21:24
I implemented code in libfolia for https://github.com/proycon/folia/issues/74.
after a small patch in ucto, it now processes the file.

**Comment by proycon** [comment] 2019-08-06 21:02
I'm reopening this because I now encounter something very similar, but on a sentence:

```
ucto: XML error: Processor 'ucto.1' is used for annotationtype 'sentence' with set='None' but there is no corresponding <annotator> referring to it in the annotation declaration block.
```

This is a situation in which there is already another sentence declaration with processor.

The full input document: ``mlp03:/scratch/proycon/wits004biog01_01.withmetadata.folia.xml`` , it does not hold actual sentences though so that is silly and something I have to look into in the tei2folia converter (hopefully the whole declaration is superfluous, but still, we might run into this problem at some point again).

**Comment by kosloot** [comment] 2019-08-06 21:23
It seems ucto doesn't pick up a 'setless' sentence-annotation correctly to add a second processor.
Have to look into this.
Should also check Frog in this respect!

**Comment by kosloot** [comment] 2019-08-07 09:22
This should be fixed in libfolia now. At the cost of messy code. Needs reviewing again

**Closed** 2019-09-04 08:06 UTC
Labels: bug
