### ISSUE TITLE
Disable word tokenization

### ISSUE THREAD

**Issue by emanjavacas** [LanguageMachines/ucto#49] opened 2018-04-20 12:07 UTC
Is it possible to disable word tokenization and only do sentence tokenization with the current version of ucto.
Given the current state of the art of sentence tokenization tools, I think this would be a pretty good contribution (and probably not too hard to implement).

best

**Comment by kosloot** [comment] 2018-04-23 07:34
Well, I thought modern Sentence Splitters already did a good job, these days. So do we need to 'downgrade' ucto to such a task? :)

OTOH implementing this feature is quite simple.
In fact, when using ucto to create FoLiA XML, a simple script to extract the sentences and then their text() will suffice. Using the C++ or Python API, that is very easy.

@proycon please comment

**Comment by proycon** [comment] 2018-04-23 08:27
Ucto's setting splitting relies on the tokenisation, so it's not easy to skip. But, if all you are interested in is the sentences (untokenised), then this information is indeed simply available from the FoLiA output.

**Comment by emanjavacas** [comment] 2018-04-23 09:01
Most people seem to rely on nltk built-in punk tokenizer, which has been reported to not be exactly great. There is also splitta, which is kind of outdated and written in python2. It'd be great to be able to use just ucto for this, plain text input to plain text output, without any further workarounds. (I am unsure about the Folia solution, since I need to process pretty large files, and I imagine Folia would have trouble dealing with very large trees?)

**Comment by emanjavacas** [comment] 2018-04-23 09:38
Thanks a lot!

**Comment by kosloot** [comment] 2018-04-30 10:41
OK. In the GIT master branch, ucto now has an --split option. It seems to do what @emanjavacas intended. Feedback is welcome!

**Comment by emanjavacas** [comment] 2018-04-30 13:56
Cool, seems to work fine! Only thing I've noticed is that if I set the -n option (one sentence per line) an extra empty line gets output in between lines. I guess that option is not very meaningful in this context anyway.

Thanks for implementing this!

**Comment by kosloot** [comment] 2018-04-30 14:26
Yeah, I saw that too.
Thought it wouldn't hurt :)

closing this issue then.

**Closed by kosloot** 2018-04-30 14:26 UTC
Labels: Testing...
